### ISSUE TITLE
sensors unavailable since 2025.6.1

### ISSUE THREAD

**Issue by carlmartens05** [elden1337/hass-peaqnext#32]
Hello, all of my peaqnext sensors are unavailable since I updated to 2025.6.1.
Is there a way to resolve this?

Logbook:
Logger: homeassistant.config_entries
Bron: config_entries.py:749
Eerst voorgekomen: 22:15:21 (11 gebeurtenissen)
Laatst gelogd: 22:19:47

Error setting up entry Droger Eco for peaqnext
Error setting up entry goedkoopste 2 uur/12uur for peaqnext
Error setting up entry plug in battery 1 for peaqnext
Error setting up entry vaatwasser eco normaal for peaqnext
Error setting up entry Peaqnext-sensors for peaqnext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/peaqnext/__init__.py", line 35, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(conf, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

kind regards,
Carl

**Comment by elden1337** [comment]
https://github.com/elden1337/hass-peaqnext/releases/tag/0.5.8

New release with fix.
